insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (1, 2, 13, 2, 11, 'Azuay', 'Cuenca');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (2, 15, 1, 2, 15, 'Carchi', 'Túlcan');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (3, 9, 7, 3, 15, 'Cotopaxi', 'Latacunga');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (4, 11, 11, 12, 5, 'Chimborazo', 'Riobamba');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (5, 6, 4, 9, 15, 'Esmeraldas', 'Esmeraldas');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (6, 11, 4, 4, 4, 'Guayas', 'Guayaquil');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (7, 6, 8, 9, 15, 'El Oro', 'Machala');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (8, 9, 8, 7, 13, 'Los Ríos', 'Quevedo');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (9, 2, 4, 5, 8, 'Loja', 'Loja');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (10, 3, 1, 1, 3, 'Napo', 'Tena');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (11, 3, 15, 11, 2, 'Manabí', 'Manta');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (12, 1, 12, 12, 14, 'Manabí', 'Portoviejo');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (13, 5, 6, 14, 9, 'Morona Santiago', 'Macas');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (14, 7, 12, 6, 5, 'Pichincha', 'Quito');
insert into SUCURSAL (SUCURSAL_ID  , CLI_ID  , ENV_ID  , TRANS_ID, VEHICULO_ID   , SU_PROVINCIA , SU_CIUDAD ) values (15, 3, 3, 8, 3, 'Sucumbios', 'Nueva Loja');
